# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # npm packages
  - package-ecosystem: 'npm'
    directory: '/app/legacy'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps(legacy-npm): '
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/app/main'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps(main-npm): '
    groups:
      dependencies:
        patterns:
          - '*'

  # rust packages
  - package-ecosystem: 'cargo'
    directory: '/core_lib'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps(core_lib): '
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'cargo'
    directory: '/app/legacy/src-tauri'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps(legacy-rust): '
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'cargo'
    directory: '/app/main/src-tauri'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps(main-rust): '
    groups:
      dependencies:
        patterns:
          - '*'

  # github actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps(actions): '
    groups:
      dependencies:
        patterns:
          - '*'