// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";

export type EndpointInfo = { fullname: string, id: string, name: string | null, ip: string | null, port: string | null, rtype: DeviceType | null, present: boolean | null, };
