// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";

export interface RemoteDeviceInfo { name: string, device_type: DeviceType, }
