// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutboundPayload } from "./OutboundPayload";

export type SendInfo = { id: string, name: string, addr: string, ob: OutboundPayload, };
