// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteDeviceInfo } from "./RemoteDeviceInfo";

export interface TransferMetadata { id: string, destination: string | null, source: RemoteDeviceInfo | null, files: Array<string> | null, pin_code: string | null, text_description: string | null, }