// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TransferMetadata { id: string, files: Array<string>, pin_code: string | null, text_description: string | null, }
