name: r-quick-share
base: core20
version: 0.11.0
summary: QuickShare implementation for Linux
description: |
  Rust implementation of NearbyShare/QuickShare from Android for Linux.
grade: devel
confinement: strict
apps:
  r-quick-share:
    command: r-quick-share
    extensions:
      - gnome-3-38
    plugs:
      - bluez
      - home
      - network
      - network-bind
      - desktop
parts:
  dump-binary:
    plugin: dump
    source: ./app/legacy/src-tauri/target/release
    source-type: local
    stage:
      - lib
      - r-quick-share
    prime:
      - lib
      - r-quick-share
    stage-packages:
      - libc6
